server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: turnos
          uri: http://turnos:8081
          predicates:
            - Path=/api/turnos/**
          filters:
            - StripPrefix=1

        - id: pacientes
          uri: http://pacientes:8082
          predicates:
            - Path=/api/pacientes/**
          filters:
            - StripPrefix=1

        - id: medicos
          uri: http://medicos:8083
          predicates:
            - Path=/api/medicos/**
          filters:
            - StripPrefix=1

        - id: notificaciones
          uri: http://notificaciones:8084
          predicates:
            - Path=/api/notificaciones/**
          filters:
            - StripPrefix=1

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,info
